var scriptUpdate = {
colorTxt: '0.2.9.8',
colorTxtNew: '"dayofdead!" and "independence!" icon added',
quicksearch: '1.4.8',
quicksearchNew: 'Bugfix for sorting method<br><br><b>v1.4.7:</b><br>New sets & items (veteran shop & Easter event 2017 - TW v2.53)',
TWLT: '1.38',
TWLTNew: '-New feature: SkipOpen - Open a common bag with one click. The confirmation and result message will be skipped.<br>-New feature: ShortPopups - Make the item popups shorter<br>-BonusSearch: find now all items with a selected bonus, too<br>-EquipManager+: When rename a set, the name is already in textfield',
Tweaker: '0.1.19',
TweakerNew: '-Better data saving<br>-Export and import added',
GoldJobs: '1.09',
GoldJobsNew: 'New forum links<br><br><b>If you\'re redirected to Greasyfork, just hit the Install button there to get the update.</b>',
npcLocator: '1.1.5',
npcLocatorNew: 'Turkish added',
TWS: '1.2.1',
TWSNew: 'Regeneration timer:<br>-You can see now, how much percent is left to max health/energy.<br>-See how much time left for next health/energy point.',
TWM: '4.159',
BS: '1.0.12',
BSNew: 'Polish added',
TWNotifier: '1.020',
TWNotifierNew: 'New event - nick in chat:<br>You get a sound when your nickname is mentioned in the chat.',
twmbb: '0.4.7',
twmbbNew: '-Better data saving<br>-Recipes work now',
KoM: '1.73',
KoMNew: '-Fixed performance<br>-Fixed message when multiple battles<br>-Better updater',
InvBuff: '2.34',
InvBuffNew: 'Last update for this script!',
DJ: '2.3.5',
DJNew: '',
};
