var scriptUpdate = {
colorTxt: '0.2.9.5',
colorTxtNew: 'little',
InvBuff: '2.34',
InvBuffNew: 'Last update for this script!',
quicksearch: '1.3.6',
quicksearchNew: 'New sets & items (Independence event 2016 - TW v2.37)',
TWLT: '1.30.1',
TWLTNew: 'SetBonus/BonusSearch: Not yet public sets now hidden on Beta, too',
Tweaker: '0.1.17',
TweakerNew: 'Topic of alliance-chat also supported',
GoldJobs: '1.08',
GoldJobsNew: 'BBcode export is now shorter and in alphabetical order<br><br><b>If the message appears more than once, you have 2 Gold Jobs scripts installed.<br>Remove the old one!</b>',
npcLocator: '1.1.1',
npcLocatorNew: '',
TWS: '1.1.5',
TWSNew: 'All the old features are working again!',
DJ: '2.3.4',
TWM: '4.156',
BS: '1.0.12',
BSNew: 'Polish added',
TWNotifier: '1.011',
TWNotifierNew: 'Portuguese added',
};
